name: Run PHP CodeSniffer

# Run PHPCBF to fix changes and commit the fixes.

on:
  push:
    branches:
      - main
    paths:
      - '**.php'

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr

      - name: Run composer install
        run: composer install

      # TODO: Only run PHPCBF on files that have been changed.

      - name: Run PHPCBF to fix what it can
        continue-on-error: true # It may not fix all the changes, in which case it will return a non-zero error code, but we still want to commit the automatic fixes.
        run: vendor/bin/phpcbf

      - name: Commit PHPCBF changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 PHPCBF"
